#+ORG2BLOG:
#+DATE: [2018-06-18 Mon 13:57]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Uncategorized, Hello
#+TAGS:
#+DESCRIPTION:
#+TITLE: Pensées sur l'échec de Gustavo Petro à l'élection présidentielle de 2018

Je songeais à éviter les écrits politiques sur la Colombie jusqu'à
atteindre l'age de trente ans: Après être passionné par la candidature
d'Antanas Mockus aux presidentielles de 2010---suivant chaque débat,
ecrivant sur les réseaux sociaux activement pour le soutenir (à ce moment
j'étais boursier du gouvernent coreenne à l'université nationale de
Séoul)---, j'avais décidé de me concetrer sur mes études d’économie.

Aujourd'hui, 18 juin 2018, je décide de reprendre la plume. Les mots
s'entasse dans mon cœur, et j'ai besoin d'exprimer ces sentiments. Un jour
de ma viellisse, je vais relire, et j'y vais retourner. La politique est
pleine de désillusions pour nous, les révolutionnaires. Heureusement que je
suis historien: le temps n'est jamais si long qu'il ne le semble. 


